### ISSUE TITLE
sphinx_glpi_theme vs sphinx_rtd_theme

### ISSUE THREAD

**Issue by venaturum** [glpi-project/sphinx_glpi_theme#2]
Hi,

I've come across a project which is using sphinx_glpi_theme, and I'm interested to understand what the difference is between it, and sphinx_rtd_theme on which it is based?

Thanks!

**Comment by trasher** [comment]
Hi,

This theme is based on readthedocs one; with a very few config changed per default, addition of a fancybox JS script - well, as far as I remember; this has been done years ago :)

**Comment by venaturum** [comment]
Ta, thanks!
